default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: recruitment-task_development

test:
  <<: *default
  database: recruitment-task_test

production:
  <<: *default
  database: recruitment-task_production
  username: recruitment-task
  password: <%= ENV['RECRUITMENT-TASK_DATABASE_PASSWORD'] %>
